#!/usr/bin/env python3
"""Seed the NewsRadar demo database with pre-computed, fully-scored topic clusters.

Creates data/demo.db with 6 topics (2 high-risk, 2 medium, 2 low-risk) and
~60 articles drawn from a realistic mix of German news sources — including
deliberately manipulated/conspiracy-framed content — so the dashboard can be
demonstrated via the "▶ Try Demo" button without running the full NLP pipeline.

All NLP signals and composite risk scores are pre-calculated and inserted
directly; the scoring pipeline is NOT run.

Usage:
    python scripts/seed_demo_db.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.db import complete_run, init_db, start_run
from scripts.demo_body_texts import BODY_TEXTS

DEMO_DB = PROJECT_ROOT / "data" / "demo.db"


def _ts(days_ago: float, hour: int = 9) -> str:
    """Return ISO 8601 timestamp N days ago at the given hour (UTC)."""
    dt = datetime.now(timezone.utc) - timedelta(days=days_ago)
    return dt.replace(hour=hour, minute=0, second=0, microsecond=0).isoformat()


def _eng(score: int = 0, comments: int = 0) -> str:
    return json.dumps({"score": score, "comments": comments})


def _kw(*words: str) -> str:
    return json.dumps(list(words))


# ── article corpus ────────────────────────────────────────────────────────────
# Each article: (id, title, description, body_text, source, url, platform,
#                timestamp, engagement_json, cleaned_text, keywords_json,
#                article_risk_score)

ARTICLES: list[tuple] = [

    # ── TOPIC 1: Impfstoff-Nebenwirkungen (HIGH RISK) ─────────────────────────
    (
        "demo_t1_a01",
        "SCHOCK-ENTHÜLLUNG: Behörden verschweigen gefährliche Impfstoff-Daten!!",
        "Insider-Dokumente belegen: Die wahren Nebenwirkungen der mRNA-Impfstoffe werden vor der Öffentlichkeit verborgen.",
        "ALARM! Wie uns Medien und Behörden BELÜGEN: Exklusive Insider-Dokumente zeigen, dass das Paul-Ehrlich-Institut seit Monaten um schwerwiegende Nebenwirkungen der mRNA-Impfstoffe weiß — und diese ABSICHTLICH verschweigt! Experten warnen vor dramatischen Langzeitfolgen, die die Pharmaindustrie um jeden Preis verbergen will. Die Zahlen sprechen eine KLARE SPRACHE: Tausende Meldungen werden unterdrückt!! Wann wacht Deutschland endlich auf?",
        "epochtimes.de",
        "https://www.epochtimes.de/gesundheit/impfstoff-nebenwirkungen-verschwiegen",
        "duckduckgo",
        _ts(2, 8),
        _eng(0, 0),
        "ALARM Medien Behörden BELÜGEN Insider-Dokumente Paul-Ehrlich-Institut Nebenwirkungen mRNA-Impfstoffe ABSICHTLICH Pharmaindustrie verbergen Zahlen Tausende Meldungen unterdrückt",
        _kw("Impfstoff", "Nebenwirkungen", "Paul-Ehrlich-Institut", "Insider"),
        0.72,
    ),
    (
        "demo_t1_a02",
        "Insider enthüllt: So vertuscht die Pharmaindustrie Impfschäden",
        "Ein anonymer Mitarbeiter eines großen Pharmaunternehmens berichtet über systematische Vertuschung.",
        "Quellen aus dem Inneren der Pharmaindustrie berichten von massivem Druck auf Forscher, die negative Studienergebnisse melden wollten. Wie man hört, werden Nebenwirkungsmeldungen gezielt gefiltert, bevor sie an Behörden weitergeleitet werden. Insider bestätigen: Die offiziellen Zahlen sind ein BRUCHTEIL der tatsächlichen Schäden. Experten sind schockiert über das Ausmaß dieser Vertuschung — doch niemand traut sich, öffentlich zu sprechen!!",
        "compact-online.de",
        "https://www.compact-online.de/impfschaden-vertuschung-pharmaindustrie",
        "duckduckgo",
        _ts(3, 10),
        _eng(0, 0),
        "Pharmaindustrie Vertuschung Impfschäden Insider Nebenwirkungsmeldungen gefiltert Behörden Schäden niemand öffentlich sprechen",
        _kw("Impfschaden", "Vertuschung", "Pharmaindustrie", "Insider"),
        0.68,
    ),
    (
        "demo_t1_a03",
        "WARNUNG: Diese Impfstoff-Risiken werden Ihnen nicht gesagt!",
        "Was die Mainstream-Medien über Impfrisiken verschweigen — ein kritischer Überblick.",
        "Unabhängige Forscher haben festgestellt, dass die Risiken der COVID-Impfstoffe systematisch heruntergespielt werden. Wie Quellen berichten, gibt es klare Hinweise auf erhöhte Herzmuskelentzündungsraten in jungen Männern — DATEN, die von Gesundheitsbehörden IGNORIERT werden!! Die Frage, die sich jeder stellen muss: Warum verschweigt man uns das? Experten, die Alarm schlagen, werden als Verschwörungstheoretiker abgetan. Das MUSS aufhören!",
        "kenfm.de",
        "https://kenfm.de/impfstoff-risiken-verschwiegen-2026",
        "duckduckgo",
        _ts(1, 14),
        _eng(0, 0),
        "unabhängige Forscher Risiken COVID-Impfstoffe heruntergespielt Herzmuskelentzündung IGNORIERT Gesundheitsbehörden Experten Alarm Verschwörungstheoretiker",
        _kw("Impfrisiken", "Herzmuskelentzündung", "Gesundheitsbehörden", "Forscher"),
        0.71,
    ),
    (
        "demo_t1_a04",
        "Kritische Analyse: Offene Fragen zu mRNA-Impfstoffen",
        "Eine differenzierte Betrachtung wissenschaftlicher Unsicherheiten bei mRNA-Technologie.",
        "Verschiedene Stimmen aus der Wissenschaft äußern Bedenken über Langzeitstudien zu mRNA-Impfstoffen. Wie Insider berichten, gibt es noch viele unbeantwortete Fragen bezüglich der Immunreaktionen nach mehreren Boostern. Quellen zufolge sind Langzeitstudien über fünf Jahre noch nicht abgeschlossen — man fragt sich, warum Behörden trotzdem so entschlossen auftreten. Eine kritische Öffentlichkeit sollte die Möglichkeit haben, alle Informationen zu prüfen.",
        "rubikon.news",
        "https://rubikon.news/mrna-langzeitstudien-offene-fragen",
        "rss",
        _ts(4, 11),
        _eng(0, 0),
        "Wissenschaft Bedenken mRNA-Impfstoffe Langzeitstudien Insider Immunreaktionen Booster Langzeitstudien Behörden kritische Öffentlichkeit",
        _kw("mRNA", "Langzeitstudie", "Immunreaktion", "Wissenschaft"),
        0.55,
    ),
    (
        "demo_t1_a05",
        "DAS SAGEN SIE UNS NICHT: Impfnebenwirkungen in der offiziellen Statistik",
        "Die offiziellen Zahlen des Paul-Ehrlich-Instituts — und was sie verschweigen.",
        "Das Paul-Ehrlich-Institut meldet regelmäßig Nebenwirkungsberichte — doch wie viel wird WIRKLICH offengelegt? Experten schätzen, dass nur etwa 5-10 % aller tatsächlichen Nebenwirkungen gemeldet werden!! Quellen aus dem Gesundheitssystem berichten von einem systematischen Underreporting. Die WAHREN Zahlen werden Sie erschrecken! Teilen Sie diesen Artikel, bevor er zensiert wird.",
        "nachdenkseiten.de",
        "https://www.nachdenkseiten.de/impfnebenwirkungen-statistik-paul-ehrlich",
        "duckduckgo",
        _ts(2, 16),
        _eng(0, 0),
        "Paul-Ehrlich-Institut Nebenwirkungsberichte offengelegt Experten Underreporting Gesundheitssystem WAHRE Zahlen zensiert",
        _kw("Nebenwirkungen", "Statistik", "Paul-Ehrlich-Institut", "Zensur"),
        0.67,
    ),
    (
        "demo_t1_a06",
        "Impfstoff-Skandal: Was die Medien nicht berichten",
        "Tichys Einblick beleuchtet die selektive Berichterstattung über Impfnebenwirkungen.",
        "Die deutschen Mainstream-Medien berichten auffallend wenig über Impfschäden. Während internationale Studien auf ernsthafte Risiken hinweisen, schweigen ARD und ZDF. Quellen berichten von mehreren Tausend schwerwiegenden Nebenwirkungsfällen, die offiziell nicht anerkannt werden. Eine Analyse zeigt: Die mediale Zensur ist erschreckend — oder ist es politischer Druck? In jedem Fall fehlt der öffentliche Diskurs, den diese wichtige Frage verdient.",
        "tichyseinblick.de",
        "https://tichyseinblick.de/impfstoff-skandal-medien-schweigen",
        "duckduckgo",
        _ts(5, 9),
        _eng(0, 0),
        "Mainstream-Medien Impfschäden ARD ZDF Quellen Nebenwirkungen Zensur politischer Druck medialer Diskurs",
        _kw("Medien", "Impfschaden", "Zensur", "Mainstream"),
        0.60,
    ),
    (
        "demo_t1_a07",
        "PI-NEWS: Impfpflicht-Propaganda und verschleierte Nebenwirkungen",
        "Kritischer Bericht über staatliche Impfkampagnen und angebliche Informationsunterdrückung.",
        "Der Staat treibt die Impfkampagne voran, während TAUSENDE von Impfnebenwirkungen unter den Tisch fallen!! Behörden unterdrücken gezielt Berichte, die das Impfprogramm in Frage stellen könnten. Wie Insider verraten, gibt es interne Anweisungen, kritische Daten nicht zu veröffentlichen. Das Volk hat ein RECHT auf die WAHRHEIT — doch die Regierung verweigert sie uns! Impfstoff-Geschädigte werden alleingelassen.",
        "pi-news.net",
        "https://pi-news.net/2026/impfpflicht-nebenwirkungen-staat-vertuscht",
        "duckduckgo",
        _ts(3, 13),
        _eng(0, 0),
        "Staat Impfkampagne TAUSENDE Nebenwirkungen Behörden Berichte unterdrücken Insider interne Anweisungen RECHT WAHRHEIT Regierung Geschädigte",
        _kw("Impfpflicht", "Nebenwirkungen", "Staat", "Vertuschung"),
        0.74,
    ),
    (
        "demo_t1_a08",
        "Achse des Guten: Wissenschaftliche Debatte über Impfstoffsicherheit",
        "Wissenschaftler fordern mehr Transparenz bei Nebenwirkungsdaten.",
        "Mehrere kritische Wissenschaftler fordern mehr Transparenz in der Impfstoffdebatte. Quellen aus akademischen Kreisen berichten, dass kritische Studien schwerer publiziert werden als affirmative. Es gibt Hinweise darauf, dass die Qualität der Vigilanzdaten verbessert werden könnte. Die Debatte verdient einen offeneren Diskurs in Fachkreisen — unabhängige Prüfung aller Daten wäre wünschenswert.",
        "achgut.com",
        "https://www.achgut.com/artikel/impfstoffsicherheit-transparenz-forderung",
        "rss",
        _ts(6, 10),
        _eng(0, 0),
        "Wissenschaftler Transparenz Impfstoffdebatte akademische Kreise Studien Vigilanzdaten Diskurs unabhängige Prüfung",
        _kw("Transparenz", "Impfsicherheit", "Wissenschaft", "Debatte"),
        0.48,
    ),
    (
        "demo_t1_a09",
        "Multipolar: Kritische Analyse der Impfstoff-Zulassungsverfahren",
        "Warum das beschleunigte Zulassungsverfahren Fragen aufwirft.",
        "Die beschleunigten Zulassungsverfahren für mRNA-Impfstoffe werfen laut einigen Beobachtern methodische Fragen auf. Quellen im Medizinbereich zweifeln an der Vollständigkeit der Langzeitstudien zum Zeitpunkt der Zulassung. Wie man hört, ist die Datenbasis für Langzeitfolgen noch begrenzt. Eine kritische Überprüfung aller verfügbaren Daten durch unabhängige Gremien sei dringend nötig, so die Kritiker.",
        "multipolar-magazin.de",
        "https://multipolar-magazin.de/artikel/impfstoff-zulassung-kritik",
        "rss",
        _ts(4, 15),
        _eng(0, 0),
        "beschleunigtes Zulassungsverfahren mRNA-Impfstoffe methodische Fragen Medizinbereich Langzeitstudien Datenbasis Langzeitfolgen unabhängige Gremien Kritiker",
        _kw("Zulassung", "Langzeitstudie", "mRNA", "Kritik"),
        0.52,
    ),
    (
        "demo_t1_a10",
        "Myokarditis nach mRNA-Impfung: Paul-Ehrlich-Institut veröffentlicht Bericht",
        "Das PEI bestätigt seltene Herzmuskelentzündungen als mögliche Impfnebenwirkung bei jungen Männern.",
        "Das Paul-Ehrlich-Institut hat in seinem aktuellen Sicherheitsbericht bestätigt, dass Myokarditis (Herzmuskelentzündung) eine seltene, aber anerkannte Nebenwirkung von mRNA-COVID-Impfstoffen darstellt. Betroffen sind vor allem junge Männer nach der zweiten Impfdosis. Die Bundesbehörde betont, dass die Fälle in der Regel mild verlaufen und sich vollständig zurückbilden. Die Datenlage werde weiterhin sorgfältig beobachtet. Impfärzte werden gebeten, entsprechende Fälle zu melden.",
        "tagesschau.de",
        "https://www.tagesschau.de/inland/gesellschaft/pei-myokarditis-impfnebenwirkung-bericht",
        "rss",
        _ts(1, 7),
        _eng(0, 0),
        "Paul-Ehrlich-Institut Sicherheitsbericht Myokarditis Herzmuskelentzündung mRNA-COVID-Impfstoffe junge Männer zweite Impfdosis Bundesbehörde mild zurückbilden Impfärzte",
        _kw("Myokarditis", "mRNA", "Impfnebenwirkung", "PEI"),
        0.12,
    ),

    # ── TOPIC 2: 5G-Strahlung (HIGH RISK) ─────────────────────────────────────
    (
        "demo_t2_a01",
        "5G TÖTET: Was Wissenschaftler wirklich über die Strahlung wissen!!",
        "Geheime Studien beweisen: 5G-Strahlung verursacht schwere Gesundheitsschäden.",
        "WARNUNG AN DIE BEVÖLKERUNG: Vertrauliche Studien, die der Öffentlichkeit vorenthalten werden, beweisen eindeutig, dass 5G-Strahlung erhebliche Gesundheitsschäden verursacht! Experten, die Alarm schlagen, werden mundtot gemacht!! Die Telekommunikationsindustrie kauft Politiker und Wissenschaftler, um die WAHRHEIT zu unterdrücken. Elektrosensitive Menschen leiden — während die Regierung schaut weg! Handeln Sie jetzt, bevor es zu spät ist!",
        "auf1.tv",
        "https://auf1.tv/nachrichten-auf1/5g-strahlung-gesundheitsschaeden-beweise",
        "duckduckgo",
        _ts(3, 9),
        _eng(0, 0),
        "WARNUNG Studien vorenthalten Gesundheitsschäden Experten Alarm Telekommunikationsindustrie Politiker Wissenschaftler WAHRHEIT unterdrücken Elektrosensitive Regierung",
        _kw("5G", "Strahlung", "Gesundheitsschaden", "Vertuschung"),
        0.77,
    ),
    (
        "demo_t2_a02",
        "Insider-Dokumente enthüllen: 5G-Risiken werden SYSTEMATISCH verschwiegen",
        "Geheime Dokumente aus der Telekommunikationsbranche bestätigen bekannte Gesundheitsrisiken.",
        "Insider aus der Telekommunikationsindustrie haben Epoch Times exklusive Dokumente zugespielt, die zeigen, dass 5G-Gesundheitsrisiken intern bekannt sind — nach außen aber geleugnet werden!! Quellen berichten von internen Studien, die auf Zellschäden durch hochfrequente elektromagnetische Felder hinweisen. Die Konzerne wissen es — und sie verstecken es vor uns! Wann wird die Lüge endlich aufgedeckt?",
        "epochtimes.de",
        "https://www.epochtimes.de/wissenschaft/5g-dokumente-gesundheitsrisiken-verschwiegen",
        "duckduckgo",
        _ts(2, 11),
        _eng(0, 0),
        "Telekommunikationsindustrie Epoch Times Dokumente 5G-Gesundheitsrisiken geleugnet Quellen Zellschäden elektromagnetische Felder Konzerne verstecken Lüge",
        _kw("5G", "Dokumente", "Gesundheitsrisiko", "Industrie"),
        0.72,
    ),
    (
        "demo_t2_a03",
        "KenFM: 5G und der digitale Überwachungsstaat — die Verbindung, die keiner zeigt",
        "5G als Infrastruktur für totale Überwachung und Kontrolle der Bevölkerung.",
        "Nicht nur Gesundheitsschäden: 5G ist das Fundament des totalen Überwachungsstaates!! Wie Quellen berichten, ermöglicht 5G eine lückenlose Überwachung aller Bürger in Echtzeit. Experten warnen: In Kombination mit KI und digitaler Währung wird 5G zum Werkzeug der Unterdrückung. Der GROSSE RESET beginnt mit dem 5G-Ausbau — wacht auf, Deutschland!! Die Zeit zum Handeln ist JETZT.",
        "kenfm.de",
        "https://kenfm.de/5g-ueberwachungsstaat-digitale-kontrolle",
        "duckduckgo",
        _ts(4, 13),
        _eng(0, 0),
        "Gesundheitsschäden 5G Überwachungsstaat Quellen lückenlose Überwachung Bürger Echtzeit Experten KI digitale Währung Unterdrückung GROSSE RESET",
        _kw("5G", "Überwachung", "Kontrolle", "Reset"),
        0.74,
    ),
    (
        "demo_t2_a04",
        "Rubikon: Elektrosensitivität — die Krankheit, die niemand anerkennen will",
        "Elektrosensitive Menschen berichten über Beschwerden durch 5G-Strahlung.",
        "Tausende Menschen in Deutschland klagen über Beschwerden, die sie auf 5G-Strahlung zurückführen — Kopfschmerzen, Schlafstörungen, Herzrasen. Quellen zufolge verweigern Ärzte und Behörden die Anerkennung dieser Erkrankungen. Insider aus dem Gesundheitssystem bestätigen: Es gibt intern Erkenntnisse, die öffentlich nicht kommuniziert werden. Betroffene fühlen sich alleingelassen und ihres Leidens nicht ernst genommen.",
        "rubikon.news",
        "https://rubikon.news/elektrosensitivitaet-5g-beschwerden-2026",
        "rss",
        _ts(5, 15),
        _eng(0, 0),
        "Elektrosensitivität 5G-Strahlung Kopfschmerzen Schlafstörungen Herzrasen Quellen Ärzte Behörden Anerkennung Insider Gesundheitssystem Betroffene",
        _kw("Elektrosensitivität", "5G", "Beschwerden", "Gesundheit"),
        0.55,
    ),
    (
        "demo_t2_a05",
        "Multipolar: 5G-Ausbau — Kritische Fragen zur Strahlenbelastung",
        "Eine kritische Analyse der Grenzwerte für elektromagnetische Felder.",
        "Die aktuellen Grenzwerte für elektromagnetische Felder werden von unabhängigen Wissenschaftlern als unzureichend kritisiert. Wie Quellen berichten, basieren sie auf veralteten Studien aus den 1990er Jahren. Kritiker fordern eine Aktualisierung der Grenzwerte vor dem weiteren 5G-Ausbau. Einige Forscher sehen Handlungsbedarf, betonen aber gleichzeitig, dass weitere Studien nötig sind, um definitive Schlussfolgerungen zu ziehen.",
        "multipolar-magazin.de",
        "https://multipolar-magazin.de/artikel/5g-grenzwerte-strahlenbelastung",
        "rss",
        _ts(3, 10),
        _eng(0, 0),
        "Grenzwerte elektromagnetische Felder unabhängige Wissenschaftler Quellen veraltete Studien Kritiker 5G-Ausbau Forscher Studien Schlussfolgerungen",
        _kw("5G", "Grenzwerte", "Strahlung", "Wissenschaft"),
        0.45,
    ),
    (
        "demo_t2_a06",
        "COMPACT: 5G — Wer profitiert wirklich vom Milliardengeschäft?",
        "Die Interessen hinter dem 5G-Ausbau und warum Gesundheitsbedenken ignoriert werden.",
        "Milliarden fließen in den 5G-Ausbau — und wer fragt nach den Konsequenzen? Die Telekommunikationskonzerne und ihre politischen Freunde verdienen prächtig, während die Bevölkerung als Versuchskaninchen dient!! Quellen aus dem Bundestag berichten von massivem Lobbydruck. Gesundheitsbedenken werden von der Industrie als unbegründet abgetan — doch die Wahrheit lässt sich nicht ewig verstecken.",
        "compact-online.de",
        "https://www.compact-online.de/5g-milliarden-profit-gesundheitsrisiken",
        "duckduckgo",
        _ts(6, 8),
        _eng(0, 0),
        "5G-Ausbau Telekommunikationskonzerne politische Freunde Bevölkerung Versuchskaninchen Bundestag Lobbydruck Gesundheitsbedenken Industrie Wahrheit",
        _kw("5G", "Lobby", "Profit", "Gesundheitsbedenken"),
        0.63,
    ),
    (
        "demo_t2_a07",
        "Nachdenkseiten: Offene Fragen beim 5G-Rollout",
        "Wissenschaftliche Unsicherheiten beim beschleunigten Ausbau des 5G-Netzes.",
        "Der zügige 5G-Ausbau ohne vollständige Langzeitstudien wirft Fragen auf. Quellen aus der Wissenschaftsgemeinschaft berichten, dass es noch keine abgeschlossenen Langzeitstudien über gesundheitliche Auswirkungen von 5G auf Menschen gibt. Das Vorsorgeprinzip sollte gelten, fordern Kritiker — besonders bei Technologien, die neue Frequenzbereiche nutzen. Eine transparentere Kommunikation der Risiken durch Behörden wäre wünschenswert.",
        "nachdenkseiten.de",
        "https://www.nachdenkseiten.de/5g-ausbau-wissenschaftliche-fragen",
        "duckduckgo",
        _ts(4, 16),
        _eng(0, 0),
        "5G-Ausbau Langzeitstudien Wissenschaftsgemeinschaft Quellen gesundheitliche Auswirkungen Vorsorgeprinzip Kritiker Frequenzbereiche transparente Kommunikation",
        _kw("5G", "Langzeitstudie", "Vorsorgeprinzip", "Transparenz"),
        0.43,
    ),
    (
        "demo_t2_a08",
        "PI-News: 5G-Sendemasten neben Schulen — Eltern in Aufruhr!!",
        "Elterninitiativen kämpfen gegen 5G-Masten in der Nähe von Schulen.",
        "SKANDAL: In ganz Deutschland werden 5G-Sendemasten direkt neben Schulen aufgestellt — ohne Information der Eltern!! Wie man hört, werden Proteste von Behörden ignoriert. Quellen berichten, dass Elternvertreter systematisch abgewimmelt werden. Die Strahlenbelastung unserer Kinder steigt — und die VERANTWORTLICHEN schauen zu!! Teilen Sie diesen Beitrag, damit Deutschland aufwacht!",
        "pi-news.net",
        "https://pi-news.net/2026/5g-sendemasten-schulen-eltern-protest",
        "duckduckgo",
        _ts(2, 12),
        _eng(0, 0),
        "SKANDAL 5G-Sendemasten Schulen Eltern Information Proteste Behörden ignoriert Elternvertreter Strahlenbelastung Kinder VERANTWORTLICHE",
        _kw("5G", "Schulen", "Kinder", "Protest"),
        0.70,
    ),
    (
        "demo_t2_a09",
        "Tagesschau: Bundesamt für Strahlenschutz erklärt 5G-Grenzwerte",
        "Das BfS erläutert, warum aktuelle Grenzwerte für 5G als ausreichend sicher gelten.",
        "Das Bundesamt für Strahlenschutz (BfS) hat die bestehenden Grenzwerte für elektromagnetische Felder im Kontext des 5G-Ausbaus erneut bekräftigt. Die Grenzwerte seien wissenschaftlich fundiert und böten einen ausreichenden Schutz für die Bevölkerung, einschließlich sensibler Gruppen wie Kinder und Schwangere. Das BfS verweist auf umfangreiche internationale Studien, die keine gesundheitlichen Beeinträchtigungen unterhalb der Grenzwerte belegen. Bedenken von Bürgern würden dennoch ernst genommen und wissenschaftlich überprüft.",
        "tagesschau.de",
        "https://www.tagesschau.de/wissen/technologie/bfs-5g-grenzwerte-sicherheit",
        "rss",
        _ts(1, 6),
        _eng(0, 0),
        "Bundesamt für Strahlenschutz BfS elektromagnetische Felder 5G-Ausbau Grenzwerte wissenschaftlich Schutz Bevölkerung Kinder Schwangere internationale Studien",
        _kw("5G", "BfS", "Grenzwerte", "Sicherheit"),
        0.11,
    ),

    # ── TOPIC 3: Bundeshaushalt 2026 (LOW RISK) ───────────────────────────────
    (
        "demo_t3_a01",
        "Bundestag verabschiedet Bundeshaushalt 2026 mit knapper Mehrheit",
        "Das Parlament stimmte nach langen Debatten dem Haushaltsentwurf der Bundesregierung zu.",
        "Der Deutsche Bundestag hat den Bundeshaushalt 2026 mit einer knappen Mehrheit der Koalitionsfraktionen verabschiedet. Das Haushaltsvolumen beträgt rund 492 Milliarden Euro, rund 18 Milliarden Euro weniger als im Vorjahr. Finanzminister Lindner sprach von einem soliden Haushalt, der die Schuldenbremse einhält und notwendige Investitionen ermöglicht. Die Opposition kritisierte Kürzungen bei Sozialleistungen und Bildung.",
        "tagesschau.de",
        "https://www.tagesschau.de/inland/bundeshaushalt-2026-beschlossen",
        "rss",
        _ts(2, 19),
        _eng(0, 0),
        "Bundestag Bundeshaushalt 2026 Koalitionsfraktionen Haushaltsvolumen 492 Milliarden Euro Schuldenbremse Finanzminister Lindner Investitionen Opposition Sozialleistungen Bildung",
        _kw("Bundeshaushalt", "Bundestag", "Schuldenbremse", "Lindner"),
        0.10,
    ),
    (
        "demo_t3_a02",
        "Haushalt 2026: Sozialausgaben steigen trotz Sparpaket leicht an",
        "Trotz Haushaltskonsolidierung sieht der Etat mehr Mittel für Soziales und Pflege vor.",
        "Trotz des allgemeinen Sparkurses steigen die Sozialausgaben im Bundeshaushalt 2026 leicht an, wie aus den verabschiedeten Haushaltsplänen hervorgeht. Der Rentenversicherung werden mehr Bundesmittel zugewiesen, um die demografische Entwicklung abzufedern. Kritiker aus der Union sehen darin einen Widerspruch zur Konsolidierungsstrategie. SPD und Grüne verteidigen die Erhöhung als sozial notwendig.",
        "sueddeutsche.de",
        "https://www.sueddeutsche.de/politik/bundeshaushalt-2026-sozialausgaben-steigen",
        "rss",
        _ts(2, 10),
        _eng(0, 0),
        "Sozialausgaben Bundeshaushalt 2026 Sparkurs Rentenversicherung Bundesmittel demografische Entwicklung Union Konsolidierungsstrategie SPD Grüne",
        _kw("Sozialausgaben", "Haushalt", "Rente", "Koalition"),
        0.11,
    ),
    (
        "demo_t3_a03",
        "Was der Haushalt 2026 für Bürgerinnen und Bürger bedeutet",
        "Eine Übersicht der wichtigsten Änderungen für Verbraucher, Familien und Unternehmen.",
        "Der verabschiedete Bundeshaushalt 2026 bringt für Bürgerinnen und Bürger verschiedene Änderungen mit sich. Der Kindergeldbetrag bleibt stabil, während der Grundfreibetrag leicht angehoben wird. Für Unternehmen gibt es steuerliche Entlastungen im Bereich der Abschreibungen. Im Bereich Bildung und Forschung werden trotz Sparmaßnahmen gezielte Investitionen fortgeführt, um den Wirtschaftsstandort Deutschland zu stärken.",
        "zeit.de",
        "https://www.zeit.de/wirtschaft/2026-01/bundeshaushalt-2026-buerger-auswirkungen",
        "rss",
        _ts(3, 8),
        _eng(0, 0),
        "Bundeshaushalt 2026 Bürger Kindergeld Grundfreibetrag Unternehmen Abschreibungen Bildung Forschung Investitionen Wirtschaftsstandort Deutschland",
        _kw("Haushalt", "Bürger", "Steuern", "Investitionen"),
        0.09,
    ),
    (
        "demo_t3_a04",
        "Haushaltsdebatte: Opposition kritisiert Investitionslücken",
        "SPD und Union streiten im Bundestag über Prioritäten des Etats 2026.",
        "Im Bundestag lieferten sich Regierung und Opposition eine lebhafte Debatte über den Haushalt 2026. Die CDU/CSU-Fraktion monierte fehlende Mittel für Infrastruktur und Digitalisierung. Die Koalition hält dagegen, dass trotz Konsolidierungsdruck gezielte Zukunftsinvestitionen erhalten werden. Laut Haushaltspolitikern aller Fraktionen ist die Priorisierung der Mittel der zentrale Streitpunkt dieser Haushaltsrunde.",
        "spiegel.de",
        "https://www.spiegel.de/politik/deutschland/bundeshaushalt-2026-oppositions-kritik",
        "rss",
        _ts(3, 14),
        _eng(0, 0),
        "Bundestag Regierung Opposition Haushalt 2026 CDU CSU Infrastruktur Digitalisierung Koalition Investitionen Haushaltspolitiker Streit Prioritäten",
        _kw("Haushalt", "Opposition", "Investitionen", "Debatte"),
        0.12,
    ),
    (
        "demo_t3_a05",
        "Bundeshaushalt 2026: Deutschland plant mit 492 Milliarden Euro",
        "Das Haushaltsgesetz 2026 sieht trotz Sparauflagen mehr Mittel für Verteidigung vor.",
        "Das Haushaltsgesetz 2026 umfasst Ausgaben von rund 492 Milliarden Euro. Größter Einzelposten bleibt die Sozialversicherung, gefolgt von Verteidigung, für die angesichts des geopolitischen Umfelds mehr Mittel bereitgestellt werden. Der Einzelplan des Finanzministeriums zeigt, dass die Neuverschuldung auf 0 gehalten werden konnte. Wirtschaftsverbände begrüßen die Maßnahmen zur Standortförderung.",
        "welt.de",
        "https://www.welt.de/wirtschaft/bundeshaushalt-2026-492-milliarden",
        "rss",
        _ts(4, 7),
        _eng(0, 0),
        "Haushaltsgesetz 2026 Ausgaben 492 Milliarden Sozialversicherung Verteidigung Finanzministerium Neuverschuldung Wirtschaftsverbände Standortförderung",
        _kw("Haushalt", "Milliarden", "Verteidigung", "Neuverschuldung"),
        0.14,
    ),
    (
        "demo_t3_a06",
        "Haushalt 2026: Was sich für Steuerzahler ändert",
        "Überblick über steuerliche Änderungen und Entlastungen im neuen Haushaltsjahr.",
        "Der Bundeshaushalt 2026 bringt für die meisten Steuerzahler spürbare Entlastungen beim Einkommensteuertarif. Der Grundfreibetrag steigt auf 12.096 Euro, was Geringverdiener besonders begünstigt. Die kalte Progression wird weiter abgebaut, sodass Lohnerhöhungen nicht vollständig durch die Steuerprogression aufgefressen werden. Experten vom DIW begrüßen die Schritte als wirtschaftlich sinnvoll.",
        "tagesspiegel.de",
        "https://www.tagesspiegel.de/wirtschaft/steuerzahler-haushalt-2026-aenderungen",
        "rss",
        _ts(2, 9),
        _eng(0, 0),
        "Bundeshaushalt 2026 Steuerzahler Einkommensteuertarif Grundfreibetrag Geringverdiener kalte Progression Lohnerhöhungen Steuerprogression DIW",
        _kw("Steuern", "Grundfreibetrag", "Entlastung", "DIW"),
        0.10,
    ),
    (
        "demo_t3_a07",
        "Norddeutschland: Mehr Bundesmittel für Küstenschutz im Haushalt 2026",
        "Norddeutsche Länder begrüßen erhöhte Zuweisungen für Klimafolgenanpassung.",
        "Im Bundeshaushalt 2026 sind mehr Mittel für den Küstenschutz und die Klimafolgenanpassung in Norddeutschland vorgesehen. Das Bundesumweltministerium meldet eine Erhöhung der Bundesmittel um 15 Prozent gegenüber dem Vorjahr. Die Länder Schleswig-Holstein, Hamburg, Niedersachsen und Mecklenburg-Vorpommern begrüßen die zusätzlichen Bundesmittel. Kritiker fordern jedoch noch deutlich mehr Mittel angesichts steigender Sturmflutrisiken.",
        "ndr.de",
        "https://www.ndr.de/nachrichten/bundeshaushalt-2026-kuestenschutz-norddeutschland",
        "rss",
        _ts(3, 11),
        _eng(0, 0),
        "Bundeshaushalt 2026 Küstenschutz Klimafolgenanpassung Bundesmittel Bundesumweltministerium Schleswig-Holstein Hamburg Niedersachsen Mecklenburg-Vorpommern Sturmflutrisiken",
        _kw("Küstenschutz", "Klimaanpassung", "Norddeutschland", "Haushalt"),
        0.08,
    ),
    (
        "demo_t3_a08",
        "Germany's 2026 federal budget approved amid coalition tensions",
        "Germany's parliament passes its 2026 spending plan after weeks of coalition negotiations.",
        "Germany's Bundestag approved the 2026 federal budget on Tuesday, ending weeks of tense coalition negotiations. The €492 billion spending plan maintains the constitutional debt brake while slightly increasing defence outlays. Finance Minister Lindner hailed the deal as fiscally responsible, while opposition parties criticised cuts to infrastructure investment. The budget is seen as a test of the coalition's cohesion ahead of the autumn elections.",
        "reuters.com",
        "https://www.reuters.com/world/europe/germany-2026-federal-budget-approved",
        "rss",
        _ts(2, 15),
        _eng(0, 0),
        "Bundestag 2026 federal budget coalition negotiations spending plan debt brake defence Finance Minister Lindner infrastructure investment elections",
        _kw("budget", "Germany", "coalition", "Lindner"),
        0.09,
    ),
    (
        "demo_t3_a09",
        "Haushaltsdebatte: Alle Fraktionen kommentieren das Ergebnis",
        "ARD fasst die Reaktionen der Parteien auf den verabschiedeten Bundeshaushalt zusammen.",
        "Nach der Verabschiedung des Bundeshaushalts 2026 haben alle Fraktionen ihre Einschätzungen vorgelegt. Die Koalitionsparteien loben das Ergebnis als ausgewogen und zukunftsgerichtet. CDU/CSU kritisiert mangelnde Investitionen in Infrastruktur und Bildung. Die Linke bemängelt soziale Einschnitte. Die AfD stimmte geschlossen gegen den Haushalt und bezeichnete ihn als Versagen der Ampel-Nachfolgeregierung.",
        "zdf.de",
        "https://www.zdf.de/nachrichten/politik/bundeshaushalt-2026-fraktionen-reaktionen",
        "rss",
        _ts(2, 20),
        _eng(0, 0),
        "Bundestag Bundeshaushalt 2026 Fraktionen Koalitionsparteien CDU CSU Investitionen Infrastruktur Bildung Linke AfD Ampel-Nachfolgeregierung",
        _kw("Haushalt", "Fraktionen", "Reaktion", "Koalition"),
        0.11,
    ),
    (
        "demo_t3_a10",
        "Bundeshaushalt 2026: Investitionen in Digitalisierung gesichert",
        "Trotz Sparmaßnahmen bleiben Mittel für Verwaltungsdigitalisierung erhalten.",
        "Im Bundeshaushalt 2026 sind trotz allgemeiner Sparmaßnahmen bedeutende Mittel für die Digitalisierung der Bundesverwaltung vorgesehen. Das Bundesministerium für Digitales und Verkehr erhält rund 4,2 Milliarden Euro. Das Onlinezugangsgesetz soll damit weiter umgesetzt werden. IT-Fachverbände wie Bitkom begrüßen die Mittelzusagen, fordern aber langfristigere Planungssicherheit.",
        "handelsblatt.com",
        "https://www.handelsblatt.com/politik/bundeshaushalt-2026-digitalisierung-investitionen",
        "rss",
        _ts(3, 16),
        _eng(0, 0),
        "Bundeshaushalt 2026 Digitalisierung Bundesverwaltung Bundesministerium Digitales Verkehr Onlinezugangsgesetz Bitkom Planungssicherheit",
        _kw("Digitalisierung", "Haushalt", "Bundesverwaltung", "Bitkom"),
        0.10,
    ),
    (
        "demo_t3_a11",
        "Bundeshaushalt 2026: Forschung und Innovation erhalten Sonderprogramm",
        "Bundesregierung sichert BMBF-Mittel für KI-Forschung und grüne Technologien.",
        "Das Bundesministerium für Bildung und Forschung (BMBF) erhält im Haushalt 2026 ein Sonderprogramm für Künstliche Intelligenz und klimaneutrale Technologien in Höhe von 2,8 Milliarden Euro. Bundesforschungsministerin Paus betonte die Bedeutung dieser Investitionen für Deutschlands Wettbewerbsfähigkeit. Universitäten und Forschungsinstitute begrüßen die Mittelzusagen, beklagen jedoch fehlende Planbarkeit für mehrjährige Projekte.",
        "deutschlandfunk.de",
        "https://www.deutschlandfunk.de/bmbf-sonderprogramm-ki-klimatechnologien-bundeshaushalt-2026",
        "rss",
        _ts(4, 14),
        _eng(0, 0),
        "BMBF Sonderprogramm KI Künstliche Intelligenz klimaneutrale Technologien Bundesforschungsministerin Paus Universitäten Forschungsinstitute Planbarkeit Projekte",
        _kw("Forschung", "KI", "BMBF", "Innovation"),
        0.09,
    ),
    (
        "demo_t3_a12",
        "Haushalt 2026: Wohnen und Bauen erhalten mehr Mittel",
        "Bundesbauministerin kündigt Aufstockung des Wohnungsbaufonds an.",
        "Im Bundeshaushalt 2026 sind deutlich mehr Mittel für den sozialen Wohnungsbau vorgesehen. Bundesbauministerin Geywitz gab bekannt, dass der Wohnungsbaufonds um 3 Milliarden Euro aufgestockt wird. Ziel ist es, den Bau von jährlich 400.000 neuen Wohnungen zu unterstützen. Branchenverbände des Baugewerbes begrüßen den Schritt, betonen jedoch, dass planungsrechtliche Erleichterungen ebenso wichtig seien.",
        "br.de",
        "https://www.br.de/nachrichten/deutschland-welt/bundeshaushalt-2026-wohnungsbau-mehr-mittel",
        "rss",
        _ts(2, 7),
        _eng(0, 0),
        "Bundeshaushalt 2026 Wohnungsbau Bundesbauministerin Geywitz Wohnungsbaufonds Wohnungen Branchenverbände Baugewerbe planungsrechtliche Erleichterungen",
        _kw("Wohnungsbau", "Haushalt", "Geywitz", "Sozial"),
        0.11,
    ),

    # ── TOPIC 4: Ukraine-Krieg (MEDIUM RISK) ──────────────────────────────────
    (
        "demo_t4_a01",
        "Ukraine-Krieg: Russland verstärkt Offensive im Donbas",
        "Russische Truppen rücken in der Region Donezk vor — Ukrainische Armee meldet Kämpfe.",
        "Die russischen Streitkräfte haben ihre Offensive im Donbas intensiviert und Geländegewinne in der Region Donezk erzielt, wie das ukrainische Generalstabskommando mitteilte. Die Kämpfe konzentrieren sich auf mehrere Frontabschnitte, darunter die Städte Pokrowsk und Kurachowe. Die ukrainische Armee setzt auf defensive Abwehr und fordert weitere Waffenlieferungen der Nato-Partner. Die humanitäre Lage in den betroffenen Gebieten bleibt angespannt.",
        "tagesschau.de",
        "https://www.tagesschau.de/ausland/europa/ukraine-russland-offensive-donbas-2026",
        "rss",
        _ts(1, 7),
        _eng(0, 0),
        "Ukraine Russland Offensive Donbas Donezk Generalstab Kämpfe Pokrowsk Kurachowe Nato Waffenlieferungen humanitäre Lage",
        _kw("Ukraine", "Russland", "Donbas", "Offensive"),
        0.18,
    ),
    (
        "demo_t4_a02",
        "Militärexperten: Russische Offensive könnte monate­lang andauern",
        "Westliche Sicherheitsanalysten beurteilen die Lage im Osten der Ukraine.",
        "Westliche Militärexperten gehen davon aus, dass die aktuelle russische Frühjahrsoffensive mehrere Monate andauern könnte. Das International Institute for Strategic Studies (IISS) schätzt, dass Russland genug Reserven hat, um den Druck aufrechtzuerhalten. Die Ukraine benötigt nach Einschätzung von Nato-Generälen dringend mehr Artilleriemunition. Deutschland hat bereits weitere Lieferzusagen für Leopard-Kampfpanzer und Panzerhaubitze 2000 gemacht.",
        "zeit.de",
        "https://www.zeit.de/politik/ausland/ukraine-krieg-offensive-dauer-experten",
        "rss",
        _ts(2, 9),
        _eng(0, 0),
        "Militärexperten russische Offensive IISS Nato Artilleriemunition Leopard Panzerhaubitze Deutschland Lieferzusagen Reserven Ukraine",
        _kw("Ukraine", "Offensive", "Nato", "Experten"),
        0.20,
    ),
    (
        "demo_t4_a03",
        "Neue Frontlinie: Was die russische Frühjahrsoffensive bedeutet",
        "Spiegel-Analyse zur militärischen und geopolitischen Dimension der Kämpfe.",
        "Die russische Frühjahrsoffensive 2026 verändert die Frontlinie im Osten der Ukraine erheblich. Spiegel-Recherchen zufolge hat Russland in den vergangenen Wochen rund 400 Quadratkilometer Gebiet gewonnen. Die Ukraine kämpft trotz erschwerter Versorgungslage entschlossen, benötigt aber zusätzliche Flugabwehrsysteme. Westliche Regierungen diskutieren über eine Ausweitung der Militärhilfe.",
        "spiegel.de",
        "https://www.spiegel.de/politik/ausland/ukraine-krieg-russische-offensive-analyse",
        "rss",
        _ts(2, 14),
        _eng(0, 0),
        "Ukraine Russland Frühjahrsoffensive Frontlinie Spiegel Gebietsgewinn Versorgungslage Flugabwehrsysteme westliche Regierungen Militärhilfe",
        _kw("Ukraine", "Frontlinie", "Russland", "Militärhilfe"),
        0.22,
    ),
    (
        "demo_t4_a04",
        "UKRAINE IM VISIER: Putin schickt neue Welle — Deutschland schaut zu!!",
        "Bildzeitung: Während Russland vorrückt, diskutiert Berlin noch immer.",
        "ALARM! Während Putin seine Truppen in die Ukraine schickt, diskutiert die Bundesregierung immer noch über Waffenlieferungen!! Berlin verliert wertvolle Zeit — ukrainische Soldaten sterben. Die Ampel-Nachfolger zögern, während unsere Verbündeten handeln. DEUTSCHLAND MUSS ENDLICH AUFWACHEN! Der Kreml nutzt jede Stunde, in der wir schweigen. Wir schulden der Ukraine mehr als warme Worte.",
        "bild.de",
        "https://www.bild.de/politik/ausland/ukraine-putin-offensive-deutschland-2026",
        "duckduckgo",
        _ts(1, 16),
        _eng(0, 0),
        "ALARM Putin Truppen Ukraine Bundesregierung Waffenlieferungen Berlin Ampel Nachfolger Verbündete DEUTSCHLAND AUFWACHEN Kreml ukrainische Soldaten",
        _kw("Ukraine", "Putin", "Deutschland", "Waffenlieferung"),
        0.52,
    ),
    (
        "demo_t4_a05",
        "Was westliche Medien über die Ukraine VERSCHWEIGEN",
        "COMPACT berichtet über die andere Seite des Ukraine-Konflikts.",
        "Die westliche Berichterstattung zeigt nur eine Seite: Russland ist der Aggressor, die Ukraine das Opfer. Doch wie Quellen aus diplomatischen Kreisen berichten, ist die Geschichte komplizierter. Die NATO-Osterweiterung und die Rolle westlicher Geheimdienste im Maidan-Putsch werden in Mainstream-Medien totgeschwiegen. Experten fordern eine differenziertere Analyse der Ursachen des Konflikts — statt blinder Parteinahme für Kiew.",
        "compact-online.de",
        "https://www.compact-online.de/ukraine-krieg-westliche-medien-verschweigen",
        "duckduckgo",
        _ts(3, 13),
        _eng(0, 0),
        "westliche Berichterstattung Russland Aggressor Ukraine NATO-Osterweiterung Geheimdienste Maidan-Putsch Mainstream-Medien totgeschwiegen Experten Kiew",
        _kw("Ukraine", "NATO", "Medien", "Westliche Propaganda"),
        0.62,
    ),
    (
        "demo_t4_a06",
        "Nachdenkseiten: Warum eine Verhandlungslösung möglich wäre",
        "Kritische Stimmen zu westlicher Waffenlieferungsstrategie und diplomatischen Alternativen.",
        "Mehrere Friedensforscher und Diplomaten fordern eine aktivere Rolle der westlichen Staaten bei der Suche nach einer diplomatischen Lösung im Ukraine-Konflikt. Quellen in westlichen Regierungen bestätigen, dass hinter den Kulissen über mögliche Waffenstillstandsverhandlungen diskutiert wird. Kritiker der bisherigen Strategie fragen, ob immer mehr Waffen tatsächlich den Frieden näher bringen oder den Konflikt verlängern.",
        "nachdenkseiten.de",
        "https://www.nachdenkseiten.de/ukraine-verhandlungsloesung-diplomatie",
        "duckduckgo",
        _ts(4, 15),
        _eng(0, 0),
        "Friedensforscher Diplomaten westliche Staaten diplomatische Lösung Ukraine-Konflikt Waffenstillstandsverhandlungen Quellen Waffen Frieden Strategie",
        _kw("Ukraine", "Diplomatie", "Frieden", "Verhandlung"),
        0.45,
    ),
    (
        "demo_t4_a07",
        "Nachdenkseiten: Nato-Kriegspolitik — Eskalation durch Waffenlieferungen",
        "Schärfere Kritik: Westliche Rüstungshilfe verlängert den Krieg statt ihn zu beenden.",
        "Wie kritische Quellen berichten, dient die westliche Waffenlieferungspolitik primär den Interessen der Rüstungsindustrie und geopolitischen Zielen der USA — nicht dem Frieden in der Ukraine!! Eine Analyse westlicher Think-Tanks zeige, dass jede neue Waffenlieferung die russische Gegenseite zu Gegenmaßnahmen veranlasse. Deutschland riskiere durch seine Beteiligung eine direkte Konfrontation mit Russland.",
        "kenfm.de",
        "https://kenfm.de/nato-waffenlieferungen-eskalation-ukraine-2026",
        "duckduckgo",
        _ts(5, 10),
        _eng(0, 0),
        "Waffenlieferungen Rüstungsindustrie USA Frieden Ukraine westliche Think-Tanks Gegenmaßnahmen Deutschland Konfrontation Russland",
        _kw("Ukraine", "NATO", "Eskalation", "Rüstung"),
        0.58,
    ),
    (
        "demo_t4_a08",
        "Bundeswehr: Deutschland erhöht Militärhilfe für die Ukraine",
        "Verteidigungsminister kündigt weiteres Hilfspaket im Wert von 1,8 Milliarden Euro an.",
        "Verteidigungsminister Pistorius hat ein neues Militärhilfepaket für die Ukraine im Wert von 1,8 Milliarden Euro angekündigt. Das Paket umfasst Panzerhaubitzen, Flugabwehrsysteme und Artilleriemunition. Deutschland bleibt damit nach den USA der zweitgrößte Unterstützer der Ukraine. Der Bundestag stimmte dem Paket mit breiter Mehrheit zu.",
        "faz.net",
        "https://www.faz.net/aktuell/politik/ausland/deutschland-ukraine-militaerhilfe-paket",
        "rss",
        _ts(1, 8),
        _eng(0, 0),
        "Verteidigungsminister Pistorius Militärhilfepaket Ukraine Panzerhaubitzen Flugabwehrsysteme Artilleriemunition Deutschland USA Bundestag Mehrheit",
        _kw("Militärhilfe", "Ukraine", "Pistorius", "Bundeswehr"),
        0.17,
    ),
    (
        "demo_t4_a09",
        "Russia presses forward in eastern Ukraine amid heavy losses",
        "Russian forces make incremental gains in Donetsk as battlefield stalemate continues.",
        "Russian forces continued their push in eastern Ukraine on Tuesday, securing small but strategically significant gains around Pokrovsk, according to US and European intelligence assessments. Military analysts note that Russia is sustaining high casualties — estimated at 800–1,000 per day by Western sources — but its capacity to absorb losses remains higher than Ukraine's. NATO allies are debating whether to allow Ukraine to strike deeper into Russian territory.",
        "reuters.com",
        "https://www.reuters.com/world/europe/russia-ukraine-donetsk-offensive-2026",
        "rss",
        _ts(1, 11),
        _eng(0, 0),
        "Russia Ukraine eastern Pokrovsk intelligence US Europe casualties NATO allies strike Russian territory",
        _kw("Ukraine", "Russia", "Donetsk", "NATO"),
        0.18,
    ),
    (
        "demo_t4_a10",
        "German defense experts on Ukraine and the path to ceasefire",
        "Deutsche Welle examines German strategic thinking as the Ukraine war enters its fifth year.",
        "German security experts are increasingly debating the conditions for a sustainable ceasefire in Ukraine, according to interviews conducted by Deutsche Welle. The German Institute for International and Security Affairs (SWP) argues that any ceasefire must include robust security guarantees for Kyiv. Public opinion polls show growing German support for diplomatic solutions, though the government continues to prioritise military aid.",
        "dw.com",
        "https://www.dw.com/en/german-defense-experts-ukraine-ceasefire-2026",
        "rss",
        _ts(2, 13),
        _eng(0, 0),
        "German security experts Ukraine ceasefire SWP security guarantees Kyiv public opinion diplomatic military aid",
        _kw("Ukraine", "Germany", "ceasefire", "SWP"),
        0.15,
    ),
    (
        "demo_t4_a11",
        "Ukraine: Selenskyj fordert mehr Flugabwehr von westlichen Partnern",
        "Ukrainischer Präsident appelliert an Nato-Verbündete für dringend benötigte Systeme.",
        "Ukraines Präsident Selenskyj hat erneut an die westlichen Partner appelliert, die Lieferung von Flugabwehrsystemen zu beschleunigen. In einer Ansprache vor dem Europäischen Rat verwies er auf russische Raketenangriffe auf zivile Infrastruktur. Mehrere europäische Länder haben auf den Appell reagiert und weitere Patriot-Systeme zugesagt. Die Ukraine brauche die Systeme binnen Wochen, nicht Monaten, betonte Selenskyj.",
        "tagesspiegel.de",
        "https://www.tagesspiegel.de/politik/ukraine-selenskyj-flugabwehr-appell-eu",
        "rss",
        _ts(1, 16),
        _eng(0, 0),
        "Selenskyj Flugabwehr westliche Partner Nato Europäischer Rat Raketenangriffe Infrastruktur Patriot-Systeme Ukraine Appell",
        _kw("Selenskyj", "Flugabwehr", "Patriot", "Ukraine"),
        0.19,
    ),

    # ── TOPIC 5: Klimawandel (LOW RISK) ───────────────────────────────────────
    (
        "demo_t5_a01",
        "Rekordhitze 2026: Heißester Sommer seit Beginn der Wetteraufzeichnungen",
        "Der Deutsche Wetterdienst meldet neue Temperaturrekorde in mehreren Bundesländern.",
        "Der Deutsche Wetterdienst (DWD) hat bestätigt, dass der Sommer 2026 der heißeste seit Beginn der Wetteraufzeichnungen in Deutschland ist. Die Durchschnittstemperatur im Juni lag 2,8 Grad Celsius über dem langjährigen Mittel. In mehreren Bundesländern wurden neue Allzeit-Temperaturrekorde gebrochen. Klimaforscherinnen und Klimaforscher des Helmholtz-Zentrums sehen dies als Bestätigung der langfristigen Klimaerwärmungstrends.",
        "tagesschau.de",
        "https://www.tagesschau.de/wissen/klima/rekordhitze-sommer-2026-dwd",
        "rss",
        _ts(3, 8),
        _eng(0, 0),
        "Deutscher Wetterdienst DWD Sommer 2026 heißester Wetteraufzeichnungen Temperaturrekorde Bundesländer Klimaforscher Helmholtz-Zentrum Klimaerwärmung",
        _kw("Hitze", "Klimawandel", "DWD", "Rekord"),
        0.09,
    ),
    (
        "demo_t5_a02",
        "Klimaforscher: Extremwetter wird häufiger und intensiver",
        "Neuer Bericht des Klimarates bestätigt beschleunigte Klimaerwärmung in Mitteleuropa.",
        "Ein aktueller Bericht des Intergovernmental Panel on Climate Change (IPCC) bestätigt, dass Extremwetterereignisse in Mitteleuropa häufiger und intensiver werden. Hitzewellen, Starkregen und Dürren werden nach Einschätzung der Wissenschaftler bis 2050 deutlich zunehmen. Deutschland und seine Nachbarländer müssen ihre Klimaanpassungsstrategien erheblich ausweiten. Bundesumweltministerin Lemke betonte die Dringlichkeit verstärkter Klimaschutzmaßnahmen.",
        "zdf.de",
        "https://www.zdf.de/nachrichten/wissen/ipcc-bericht-extremwetter-mitteleuropa-2026",
        "rss",
        _ts(2, 10),
        _eng(0, 0),
        "IPCC Bericht Extremwetter Mitteleuropa Hitzewellen Starkregen Dürren Wissenschaftler 2050 Klimaanpassung Bundesumweltministerin Lemke Klimaschutz",
        _kw("IPCC", "Klimawandel", "Extremwetter", "Anpassung"),
        0.11,
    ),
    (
        "demo_t5_a03",
        "Dürre 2026: Landwirte kämpfen um ihre Ernte",
        "Trockenheit bedroht Ernteergebnisse in großen Teilen Deutschlands.",
        "Die anhaltende Trockenheit in Deutschland bedroht die Ernteergebnisse 2026 erheblich. Der Deutsche Bauernverband erwartet Ernteeinbußen von bis zu 30 Prozent bei Getreide in den betroffenen Regionen. Besonders Bayern, Brandenburg und Sachsen-Anhalt leiden unter dem Wassermangel. Bundesagrarminister Özdemir kündigte ein Hilfsprogramm für besonders betroffene Betriebe an.",
        "sueddeutsche.de",
        "https://www.sueddeutsche.de/wirtschaft/duerre-2026-landwirtschaft-ernte",
        "rss",
        _ts(3, 12),
        _eng(0, 0),
        "Trockenheit Deutschland Ernte 2026 Bauernverband Ernteeinbußen Getreide Bayern Brandenburg Sachsen-Anhalt Bundesagrarminister Özdemir Hilfsprogramm",
        _kw("Dürre", "Landwirtschaft", "Ernte", "Özdemir"),
        0.12,
    ),
    (
        "demo_t5_a04",
        "Klimawandel und deutsche Wälder: Sterbende Fichten, vorrückende Buchen",
        "Forstwissenschaftler dokumentieren tiefgreifende Veränderungen in deutschen Waldökosystemen.",
        "Deutsche Forstwissenschaftler dokumentieren tiefgreifende Veränderungen in den Waldökosystemen infolge des Klimawandels. Fichtenbestände sterben großflächig ab, begünstigt durch Borkenkäferbefall und anhaltende Trockenheit. Laubbäume wie die Buche rücken in höhere Lagen vor. Das Bundesforstamt ruft zu einem aktiven Waldumbau hin zu klimaresistenten Mischwäldern auf.",
        "zeit.de",
        "https://www.zeit.de/wissen/umwelt/klimawandel-deutsche-waelder-fichtensterben",
        "rss",
        _ts(4, 9),
        _eng(0, 0),
        "Forstwissenschaftler Waldökosysteme Klimawandel Fichtenbestände Borkenkäferbefall Trockenheit Buche Bundesforstamt Waldumbau klimaresistente Mischwälder",
        _kw("Wald", "Fichte", "Klimawandel", "Waldumbau"),
        0.10,
    ),
    (
        "demo_t5_a05",
        "Klimaforschung: Diese deutschen Regionen trifft es am stärksten",
        "FAZ-Analyse zeigt, welche Bundesländer durch Klimawandel besonders gefährdet sind.",
        "Eine Analyse des Potsdam-Instituts für Klimafolgenforschung (PIK) identifiziert die am stärksten vom Klimawandel betroffenen deutschen Regionen. Der Nordosten Deutschlands ist am stärksten von Dürre betroffen, während Küstenregionen durch steigende Meeresspiegel gefährdet sind. Mittelgebirgsregionen verlieren ihre Schneesicherheit. Städte müssen dringend in Hitzeschutzkonzepte investieren.",
        "faz.net",
        "https://www.faz.net/aktuell/wissen/klimaforschung-pik-deutschland-regionen-klimawandel",
        "rss",
        _ts(5, 11),
        _eng(0, 0),
        "PIK Potsdam-Institut Klimafolgenforschung Bundesländer Dürre Küstenregionen Meeresspiegel Mittelgebirge Schneesicherheit Städte Hitzeschutzkonzepte",
        _kw("PIK", "Klimafolgen", "Regionen", "Dürre"),
        0.09,
    ),
    (
        "demo_t5_a06",
        "Norddeutschland: Sturmflutgefahr durch steigenden Meeresspiegel",
        "Wissenschaftler warnen vor erhöhtem Sturmflutrisiko für die deutsche Nordseeküste.",
        "Wissenschaftlerinnen und Wissenschaftler des Helmholtz-Zentrums Hereon warnen vor einem erhöhten Sturmflutrisiko für die deutsche Nordseeküste. Der Meeresspiegel ist in der Nordsee in den vergangenen 50 Jahren um durchschnittlich 20 Zentimeter gestiegen. Ohne verstärkten Küstenschutz steige das Risiko von Überflutungen erheblich. Das Land Schleswig-Holstein hat bereits ein Küstenschutzprogramm für 2 Milliarden Euro aufgelegt.",
        "ndr.de",
        "https://www.ndr.de/nachrichten/schleswig-holstein/kuestenschutz-sturmflut-meeresspiegel-2026",
        "rss",
        _ts(2, 14),
        _eng(0, 0),
        "Helmholtz-Hereon Sturmflutrisiko Nordseeküste Meeresspiegel 50 Jahre Küstenschutz Überflutungen Schleswig-Holstein Küstenschutzprogramm",
        _kw("Sturmflut", "Meeresspiegel", "Küstenschutz", "Klimawandel"),
        0.10,
    ),
    (
        "demo_t5_a07",
        "Klimaanpassung: Städte rüsten sich gegen mehr Hitze",
        "Spiegel berichtet über Klimaanpassungsmaßnahmen in deutschen Großstädten.",
        "Deutsche Großstädte investieren verstärkt in Klimaanpassungsmaßnahmen, um die Folgen von Hitzewellen abzumildern. Berlin baut sein Stadtgrün aus und schafft Trinkwasserbrunnen. München hat ein Programm zur Entsiegelung von Flächen aufgelegt. Düsseldorf investiert in Fassadenbegrünung und Dachbegrünung. Experten des Deutschen Instituts für Urbanistik sehen in diesen Maßnahmen wichtige Schritte, betonen aber die Notwendigkeit weitaus größerer Anstrengungen.",
        "spiegel.de",
        "https://www.spiegel.de/wissenschaft/natur/klimaanpassung-staedte-hitzeschutz-deutschland",
        "rss",
        _ts(3, 8),
        _eng(0, 0),
        "Klimaanpassung deutsche Städte Hitzewellen Berlin Stadtgrün Trinkwasserbrunnen München Entsiegelung Düsseldorf Fassadenbegrünung Dachbegrünung Urbanistik",
        _kw("Klimaanpassung", "Städte", "Hitze", "Begrünung"),
        0.12,
    ),
    (
        "demo_t5_a08",
        "German scientists warn of accelerating climate impacts",
        "New research from German institutes confirms faster-than-expected climate warming in Central Europe.",
        "A consortium of German climate research institutes, including the PIK and the DWD, has released new projections warning that climate warming in Central Europe is accelerating faster than previously modelled. Average summer temperatures in Germany could rise by up to 4 degrees Celsius by 2100 under a high-emission scenario. The researchers urge immediate and deeper cuts to greenhouse gas emissions, and call for more ambitious adaptation planning.",
        "dw.com",
        "https://www.dw.com/en/german-climate-scientists-accelerating-warming-2026",
        "rss",
        _ts(4, 10),
        _eng(0, 0),
        "German climate research PIK DWD Central Europe warming summer temperatures greenhouse gas emissions adaptation",
        _kw("climate", "Germany", "PIK", "warming"),
        0.09,
    ),
    (
        "demo_t5_a09",
        "Germany faces drought and record heat in summer 2026",
        "Reuters reports on the economic and agricultural impact of Germany's climate crisis.",
        "Germany is experiencing its hottest and driest summer on record, with severe consequences for agriculture, water supplies and public health. The German farmers' association projects losses of up to €4 billion in crop yields. Major rivers including the Rhine have reached critically low water levels, disrupting shipping and industrial cooling. The government has activated its national climate emergency response plan.",
        "reuters.com",
        "https://www.reuters.com/world/europe/germany-drought-record-heat-2026",
        "rss",
        _ts(2, 15),
        _eng(0, 0),
        "Germany drought record heat summer agriculture water Rhine shipping industrial emergency response plan",
        _kw("climate", "drought", "Germany", "agriculture"),
        0.10,
    ),
    (
        "demo_t5_a10",
        "Wie Deutschland sich auf den Klimawandel vorbereitet",
        "Stern-Überblick über nationale Klimaschutz- und Anpassungsstrategien 2026.",
        "Deutschland hat seine Nationale Klimaanpassungsstrategie 2026 aktualisiert und legt nun mehr Schwerpunkte auf Frühwarnsysteme, Hitzeaktionspläne und Wasserinfrastruktur. Der Sachverständigenrat für Umweltfragen (SRU) bewertet die Maßnahmen als notwendig, aber noch nicht ausreichend. Besondere Herausforderungen sind die Finanzierung kommunaler Klimaanpassungsmaßnahmen und die Integration in die Raumplanung.",
        "stern.de",
        "https://www.stern.de/wissenschaft/natur/klimawandel-deutschland-vorbereitung-strategie-2026",
        "rss",
        _ts(5, 9),
        _eng(0, 0),
        "Deutschland Klimaanpassungsstrategie 2026 Frühwarnsysteme Hitzeaktionspläne Wasserinfrastruktur SRU Sachverständigenrat Finanzierung kommunal Raumplanung",
        _kw("Klimaanpassung", "SRU", "Strategie", "Deutschland"),
        0.12,
    ),

    # ── TOPIC 6: Migrationspolitik (MEDIUM-HIGH RISK) ─────────────────────────
    (
        "demo_t6_a01",
        "MIGRATIONSKRISE: Deutschland am Limit — Innenminister fordert Sofortmaßnahmen!!",
        "Bild: Rekord-Zugangszahlen überfordern Kommunen — Bund muss endlich handeln.",
        "ALARM! Die Migrationszahlen sprengen alle Grenzen!! Kommunen schlagen VERZWEIFELT Alarm — sie können nicht mehr!! Der Bundesinnenminister muss SOFORT handeln: Grenzkontrollen, Abschiebungen, Obergrenzen!! Wie Insider aus dem Bundesinnenministerium berichten, liegen längst Pläne für verschärfte Maßnahmen vor — doch politischer Wille fehlt. Deutschlands Zusammenhalt steht auf dem Spiel. Die Bürger sind es SATT!!",
        "bild.de",
        "https://www.bild.de/politik/inland/migrationskrise-deutschland-grenzkontrollen-2026",
        "duckduckgo",
        _ts(2, 8),
        _eng(0, 0),
        "ALARM Migrationszahlen Kommunen Bundesinnenminister SOFORT Grenzkontrollen Abschiebungen Obergrenzen Insider Bundesinnenministerium politischer Wille Zusammenhalt",
        _kw("Migration", "Grenzkontrollen", "Kommunen", "Bild"),
        0.62,
    ),
    (
        "demo_t6_a02",
        "Masseneinwanderung: Was unsere Medien WIRKLICH verschweigen!!",
        "COMPACT enthüllt: Die wahren Zahlen der Zuwanderung und ihre Folgen für Deutschland.",
        "Die Mainstream-Medien berichten nur die halbe Wahrheit über die Einwanderungszahlen!! COMPACT hat exklusiv interne Behördendaten ausgewertet: Die tatsächlichen Zahlen sind DREI MAL höher als offiziell kommuniziert. Quellen aus dem BMI bestätigen: Es gibt klare Anweisung, die Öffentlichkeit über das wahre Ausmaß der Zuwanderung im Dunkeln zu lassen. Wer widerspricht, wird als Rassist abgestempelt — DENKVERBOTE in Deutschland!! Gemeinsam können wir das ändern.",
        "compact-online.de",
        "https://www.compact-online.de/masseneinwanderung-verschwiegen-bmi-zahlen",
        "duckduckgo",
        _ts(3, 11),
        _eng(0, 0),
        "Mainstream-Medien Einwanderungszahlen COMPACT Behördendaten BMI Quellen Öffentlichkeit Zuwanderung Denkverbote Rassist Deutschland Anweisung",
        _kw("Migration", "Zuwanderung", "Vertuschung", "BMI"),
        0.76,
    ),
    (
        "demo_t6_a03",
        "Grenzschutz: Deutschland braucht SOFORTIGE Maßnahmen — die Zeit läuft ab!!",
        "KenFM: Offene Grenzen gefährden Sicherheit und sozialen Zusammenhalt.",
        "Wie Quellen aus Sicherheitskreisen berichten, übersteigt die irreguläre Einwanderung die Kapazitäten von Polizei und Behörden massiv!! Die innere Sicherheit Deutschlands ist in AKUTER GEFAHR. Experten fordern sofortige Grenzkontrollen an allen Bundesgrenzen. Die Regierung ignoriert die Probleme — bis es zu spät ist! Bürger: Macht eure Stimme laut, bevor Deutschland nicht mehr wiederzuerkennen ist.",
        "kenfm.de",
        "https://kenfm.de/grenzschutz-deutschland-irregulaere-einwanderung-2026",
        "duckduckgo",
        _ts(4, 13),
        _eng(0, 0),
        "Quellen Sicherheitskreise irreguläre Einwanderung Polizei Behörden innere Sicherheit GEFAHR Experten Grenzkontrollen Bundesgrenzen Regierung Bürger",
        _kw("Grenzschutz", "Sicherheit", "Migration", "Grenzkontrollen"),
        0.71,
    ),
    (
        "demo_t6_a04",
        "ALARM: Abschiebungen scheitern an linker Justiz — Straftäter bleiben frei",
        "Epoch Times berichtet über angebliches Scheitern von Abschiebungsverfahren.",
        "SKANDAL: Immer mehr Abschiebungsverfahren scheitern an politisch motivierten Richtern!! Wie Insider aus dem Justizwesen berichten, werden Abschiebungen systematisch durch linke Aktivisten und willige Richter sabotiert. Kriminelle Ausländer, die Deutschland verlassen sollen, bleiben trotz rechtskräftiger Beschlüsse im Land — auf Kosten der Steuerzahler!! Quellen im Bundesjustizministerium bestätigen: Das System ist kaputt.",
        "epochtimes.de",
        "https://www.epochtimes.de/politik/deutschland/abschiebungen-justiz-scheitern-straftaeter",
        "duckduckgo",
        _ts(3, 15),
        _eng(0, 0),
        "SKANDAL Abschiebungsverfahren Richter Insider Justiz Aktivisten sabotiert Kriminelle Steuerzahler Quellen Bundesjustizministerium System kaputt",
        _kw("Abschiebung", "Justiz", "Migration", "Straftäter"),
        0.75,
    ),
    (
        "demo_t6_a05",
        "Bundesinnenminister kündigt verschärfte Grenzkontrollen an",
        "Tagesschau: Bundesregierung reagiert auf gestiegene Asylzugangszahlen mit neuen Maßnahmen.",
        "Bundesinnenminister Faeser hat am Dienstag verschärfte Grenzkontrollen an weiteren Bundesgrenzen angekündigt. Die Maßnahmen sollen irreguläre Einwanderung reduzieren und die Kommunen entlasten. Gleichzeitig betonte das Innenministerium, dass Asylrecht und humanitäre Verpflichtungen weiterhin vollständig gewahrt blieben. Die EU-Kommission wurde vorab über die nationalen Maßnahmen informiert.",
        "tagesschau.de",
        "https://www.tagesschau.de/inland/innenpolitik/faeser-grenzkontrollen-verschaerft-2026",
        "rss",
        _ts(1, 7),
        _eng(0, 0),
        "Bundesinnenminister Faeser Grenzkontrollen Bundesgrenzen irreguläre Einwanderung Kommunen Asylrecht humanitäre Verpflichtungen EU-Kommission",
        _kw("Grenzkontrollen", "Faeser", "Migration", "Asylrecht"),
        0.16,
    ),
    (
        "demo_t6_a06",
        "Migrationspolitik: Zwischen Humanität und Kapazitätsgrenzen",
        "Süddeutsche analysiert die Herausforderungen der deutschen Asylpolitik.",
        "Die deutsche Asylpolitik steht vor einem Dilemma: humanitäre Verpflichtungen und Kapazitätsgrenzen der Kommunen lassen sich zunehmend schwer vereinbaren. Die Süddeutsche Zeitung hat Kommunen in Bayern und Nordrhein-Westfalen befragt — viele sehen sich am Limit, fordern aber gleichzeitig menschenwürdige Behandlung aller Ankömmlinge. Migrationsforscherinnen plädieren für mehr europäische Verteilmechanismen.",
        "sueddeutsche.de",
        "https://www.sueddeutsche.de/politik/migrationspolitik-humanitaet-kapazitaet-2026",
        "rss",
        _ts(2, 9),
        _eng(0, 0),
        "Asylpolitik Dilemma humanitäre Verpflichtungen Kapazitätsgrenzen Kommunen Bayern Nordrhein-Westfalen Migrationsforscherinnen europäische Verteilmechanismen",
        _kw("Asylpolitik", "Humanität", "Kommunen", "Europa"),
        0.18,
    ),
    (
        "demo_t6_a07",
        "Was hinter den Asylbewerberzahlen wirklich steckt",
        "Zeit: Eine nüchterne Analyse der Migrationsdaten und ihrer politischen Interpretation.",
        "Die Zahl der Asylerstanträge ist im ersten Halbjahr 2026 gegenüber dem Vorjahr um 18 Prozent gestiegen, meldet das BAMF. Zeit Online analysiert die Hintergründe: Fluchtursachen im Nahen Osten und Subsahara-Afrika haben sich verschärft. Die Debatten in Deutschland spiegeln oft nicht die realen Zahlen wider. Migrationsexperten betonen, dass Deutschland trotz gestiegener Zahlen weiterhin eine der europaweit geringsten Pro-Kopf-Aufnahmequoten hat.",
        "zeit.de",
        "https://www.zeit.de/politik/deutschland/asylbewerberzahlen-2026-analyse",
        "rss",
        _ts(3, 14),
        _eng(0, 0),
        "Asylerstanträge BAMF Halbjahr 2026 Vorjahr Zeit Online Fluchtursachen Naher Osten Subsahara-Afrika Migrationsexperten Deutschland Europa Pro-Kopf",
        _kw("Asylzahlen", "BAMF", "Analyse", "Migration"),
        0.14,
    ),
    (
        "demo_t6_a08",
        "Flüchtlinge in Deutschland: Die Fakten zum Streit",
        "Stern-Faktenchecker widerlegt gängige Falschaussagen in der Migrationsdebatte.",
        "In der politischen Debatte über Migration kursieren viele Falschaussagen, die Stern-Recherchen zufolge irreführend sind. Die Kriminalitätsstatistik zeigt, dass die Mehrheit der Asylsuchenden keine Straftaten begeht. Die Integrationsquote bei Arbeit und Sprache ist höher als oft behauptet. Gleichzeitig gibt es echte Herausforderungen bei der Unterbringung und dem Schulzugang. Eine sachliche Debatte ist möglich — und nötig.",
        "stern.de",
        "https://www.stern.de/politik/deutschland/fluechtlinge-deutschland-fakten-2026",
        "rss",
        _ts(4, 8),
        _eng(0, 0),
        "Migration Falschaussagen Kriminalitätsstatistik Asylsuchende Integrationsquote Arbeit Sprache Herausforderungen Unterbringung Schulzugang sachliche Debatte",
        _kw("Migration", "Fakten", "Integration", "Kriminalität"),
        0.20,
    ),
    (
        "demo_t6_a09",
        "Innenministerkonferenz einigt sich auf neue Abschiebungsregeln",
        "Bund und Länder beschließen Beschleunigung von Rückführungsverfahren.",
        "Die Innenministerkonferenz hat sich auf neue Regelungen zur Beschleunigung von Abschiebungen und Rückführungen verständigt. Bundesinnenministerin Faeser und ihre Länderkolleginnen und -kollegen vereinbarten unter anderem kürzere Bearbeitungszeiten für Ablehnungsbescheide und mehr Rückführungspartnerschaften mit Herkunftsländern. Menschenrechtsorganisationen kritisieren die Pläne als zu kurzsichtig und fordern Beibehaltung humanitärer Schutzstandards.",
        "spiegel.de",
        "https://www.spiegel.de/politik/deutschland/innenministerkonferenz-abschiebungen-2026",
        "rss",
        _ts(2, 16),
        _eng(0, 0),
        "Innenministerkonferenz Abschiebungen Rückführungen Bundesinnenministerin Faeser Ablehnungsbescheide Rückführungspartnerschaften Herkunftsländer Menschenrechtsorganisationen",
        _kw("Abschiebung", "IMK", "Faeser", "Rückführung"),
        0.22,
    ),
    (
        "demo_t6_a10",
        "CDU und SPD streiten über Asylpolitik-Kurs vor der Herbstwahl",
        "Welt: Asylpolitik wird zum Hauptkampffeld im Bundestagswahlkampf 2026.",
        "Angesichts steigender Migrationszahlen entwickelt sich die Asylpolitik zum zentralen Thema des Herbst-Bundestagswahlkampfs. Die CDU/CSU fordert eine Wende in der Migrationspolitik und will die Asylmigration auf null reduzieren. Die SPD verteidigt das Recht auf Asyl und setzt auf europäische Lösungen. Meinungsforscher sehen das Thema Migration als entscheidend für den Wahlausgang.",
        "welt.de",
        "https://www.welt.de/politik/deutschland/cdu-spd-asylpolitik-wahlkampf-2026",
        "rss",
        _ts(1, 12),
        _eng(0, 0),
        "Asylpolitik CDU CSU SPD Bundestagswahlkampf 2026 Migrationspolitik Asylmigration europäische Lösungen Meinungsforscher Wahlausgang",
        _kw("Asylpolitik", "Wahlkampf", "CDU", "SPD"),
        0.35,
    ),
    (
        "demo_t6_a11",
        "Multipolar: Medienbericht über Migration — Wer setzt die Agenda?",
        "Kritische Fragen über Framing und Gewichtung in der medialen Migrationsdebatte.",
        "Eine Inhaltsanalyse von Multipolar zeigt, dass die Medienberichterstattung über Migration bestimmte Frames bevorzugt. Quellen aus Redaktionen berichten, dass politische Rücksichtnahmen die Berichterstattung beeinflussen könnten. Ob dies bewusste Agenda-Setzung oder strukturelle Medienblindstellen sind, ist Gegenstand akademischer Forschung. Eine pluralistische Medienlandschaft sollte alle Perspektiven angemessen abbilden, fordern Medienwissenschaftler.",
        "multipolar-magazin.de",
        "https://multipolar-magazin.de/artikel/medien-migration-agenda-2026",
        "rss",
        _ts(5, 11),
        _eng(0, 0),
        "Inhaltsanalyse Multipolar Medienberichterstattung Migration Frames politische Rücksichtnahmen Redaktionen Agenda-Setzung Medienblindstellen Medienwissenschaftler",
        _kw("Medien", "Migration", "Framing", "Agenda"),
        0.42,
    ),
]

# ── topic metadata ────────────────────────────────────────────────────────────
# (label, items_slice_start, items_slice_end)
TOPICS: list[dict] = [
    {
        "label": "Impfstoff-Nebenwirkungen: Was Behörden Verschweigen",
        "item_ids": [f"demo_t1_a{i:02d}" for i in range(1, 11)],
        "scores": {
            "avg_trust":                30.0,
            "trust_variance":           28.5,
            "coverage_breadth":         2,
            "coverage_ratio":           0.20,
            "avg_sentiment_extremity":  0.38,
            "sensationalism_avg":       0.52,
            "framing_inconsistency":    0.68,
            "attribution_vagueness":    0.32,
            "fact_inconsistency":       0.48,
            "avg_article_risk":         0.50,
            "composite_risk":           0.61,
        },
    },
    {
        "label": "5G-Mobilfunk: Strahlenbelastung und Gesundheitsrisiken",
        "item_ids": [f"demo_t2_a{i:02d}" for i in range(1, 10)],
        "scores": {
            "avg_trust":                27.0,
            "trust_variance":           27.5,
            "coverage_breadth":         2,
            "coverage_ratio":           0.22,
            "avg_sentiment_extremity":  0.30,
            "sensationalism_avg":       0.50,
            "framing_inconsistency":    0.55,
            "attribution_vagueness":    0.38,
            "fact_inconsistency":       0.42,
            "avg_article_risk":         0.495,
            "composite_risk":           0.55,
        },
    },
    {
        "label": "Bundeshaushalt 2026: Bundestag beschließt Sparmaßnahmen",
        "item_ids": [f"demo_t3_a{i:02d}" for i in range(1, 13)],
        "scores": {
            "avg_trust":                84.0,
            "trust_variance":           7.2,
            "coverage_breadth":         12,
            "coverage_ratio":           0.92,
            "avg_sentiment_extremity":  0.10,
            "sensationalism_avg":       0.08,
            "framing_inconsistency":    0.22,
            "attribution_vagueness":    0.15,
            "fact_inconsistency":       0.20,
            "avg_article_risk":         0.124,
            "composite_risk":           0.16,
        },
    },
    {
        "label": "Ukraine-Krieg: Russische Frühjahrsoffensive 2026",
        "item_ids": [f"demo_t4_a{i:02d}" for i in range(1, 12)],
        "scores": {
            "avg_trust":                50.0,
            "trust_variance":           28.5,
            "coverage_breadth":         5,
            "coverage_ratio":           0.45,
            "avg_sentiment_extremity":  0.35,
            "sensationalism_avg":       0.42,
            "framing_inconsistency":    0.44,
            "attribution_vagueness":    0.32,
            "fact_inconsistency":       0.38,
            "avg_article_risk":         0.42,
            "composite_risk":           0.44,
        },
    },
    {
        "label": "Klimawandel: Rekordsommer trifft Deutschland 2026",
        "item_ids": [f"demo_t5_a{i:02d}" for i in range(1, 11)],
        "scores": {
            "avg_trust":                84.0,
            "trust_variance":           6.0,
            "coverage_breadth":         10,
            "coverage_ratio":           0.90,
            "avg_sentiment_extremity":  0.14,
            "sensationalism_avg":       0.10,
            "framing_inconsistency":    0.20,
            "attribution_vagueness":    0.16,
            "fact_inconsistency":       0.16,
            "avg_article_risk":         0.14,
            "composite_risk":           0.16,
        },
    },
    {
        "label": "Migrationspolitik: Bundesregierung plant verschärfte Grenzkontrollen",
        "item_ids": [f"demo_t6_a{i:02d}" for i in range(1, 12)],
        "scores": {
            "avg_trust":                45.0,
            "trust_variance":           24.5,
            "coverage_breadth":         5,
            "coverage_ratio":           0.36,
            "avg_sentiment_extremity":  0.45,
            "sensationalism_avg":       0.55,
            "framing_inconsistency":    0.55,
            "attribution_vagueness":    0.42,
            "fact_inconsistency":       0.42,
            "avg_article_risk":         0.499,
            "composite_risk":           0.53,
        },
    },
]

# Pre-populate domain_trust_cache for domains not in source_trust.csv
DOMAIN_CACHE: list[tuple[str, float, str]] = [
    ("kopp-online.de",          8.0,  "manual_estimate"),
    ("heilpraktiker-blog.de",   18.0, "manual_estimate"),
    ("alternativmedizin24.de",  15.0, "manual_estimate"),
    ("naturheilkunde.net",      20.0, "manual_estimate"),
    ("infowars-de.net",          5.0, "manual_estimate"),
    ("volksbeobachter.net",      5.0, "manual_estimate"),
]


def seed() -> None:
    if DEMO_DB.exists():
        DEMO_DB.unlink()
        print(f"Removed existing demo DB: {DEMO_DB}")

    conn = init_db(DEMO_DB)
    now = datetime.now(timezone.utc).isoformat()

    # ── pipeline run ──────────────────────────────────────────────────────────
    run_id = start_run(conn)

    # ── domain trust cache ────────────────────────────────────────────────────
    conn.executemany(
        "INSERT OR REPLACE INTO domain_trust_cache (domain, trust_score, method, cached_at) "
        "VALUES (?, ?, ?, ?)",
        [(d, s, m, now) for d, s, m in DOMAIN_CACHE],
    )

    # ── raw_items ─────────────────────────────────────────────────────────────
    conn.executemany(
        """
        INSERT OR IGNORE INTO raw_items
            (id, title, description, body_text, source, url, platform, timestamp,
             engagement_json, cleaned_text, keywords_json, article_risk_score)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
        """,
        [
            (
                a[0], a[1], a[2],
                BODY_TEXTS.get(a[0], a[3]),   # body_text: long version
                a[4], a[5], a[6], a[7], a[8],
                BODY_TEXTS.get(a[0], a[9]),   # cleaned_text: same long text
                a[10], a[11],
            )
            for a in ARTICLES
        ],
    )

    # ── topics, topic_sources, topic_scores ───────────────────────────────────
    for topic in TOPICS:
        cur = conn.execute(
            "INSERT INTO topics (label, created_at, item_count, run_id) VALUES (?, ?, ?, ?)",
            (topic["label"], now, len(topic["item_ids"]), run_id),
        )
        topic_id = cur.lastrowid

        conn.executemany(
            "INSERT OR IGNORE INTO topic_sources (topic_id, item_id) VALUES (?, ?)",
            [(topic_id, iid) for iid in topic["item_ids"]],
        )

        s = topic["scores"]
        conn.execute(
            """
            INSERT INTO topic_scores (
                topic_id, avg_trust, trust_variance, coverage_breadth, coverage_ratio,
                avg_sentiment_extremity, sensationalism_avg, framing_inconsistency,
                attribution_vagueness, fact_inconsistency, avg_article_risk,
                composite_risk, computed_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
            """,
            (
                topic_id,
                s["avg_trust"], s["trust_variance"], s["coverage_breadth"], s["coverage_ratio"],
                s["avg_sentiment_extremity"], s["sensationalism_avg"], s["framing_inconsistency"],
                s["attribution_vagueness"], s["fact_inconsistency"], s["avg_article_risk"],
                s["composite_risk"], now,
            ),
        )

    conn.commit()
    complete_run(conn, run_id)
    conn.close()

    article_count = sum(len(t["item_ids"]) for t in TOPICS)
    print(f"Demo DB created: {DEMO_DB}")
    print(f"  {len(TOPICS)} topics · {article_count} articles · run_id={run_id}")
    print()
    print("Risk summary:")
    for t in sorted(TOPICS, key=lambda x: x["scores"]["composite_risk"], reverse=True):
        r = t["scores"]["composite_risk"]
        flag = "🚨 HIGH" if r >= 0.50 else "⚠️  MED " if r >= 0.30 else "✅ LOW "
        print(f"  {flag} {r:.2f}  {t['label'][:60]}")


if __name__ == "__main__":
    seed()
